import palette from "./palette";

export default {
  bodyBackground: palette.themeTertiary,
  bodyText: palette.white,
  bodySubtext: palette.light,
  border: palette.light,
  link: palette.themePrimary,
  linkHover: palette.themeSecondary,
  heading: palette.light,
  itemPrimary: palette.white,
  itemSecondary: palette.light,
  itemPrimaryHover: palette.black,
  itemSecondaryHover: palette.dark,
  itemBackground: palette.dark,
  itemBackgroundHover: palette.light,
  liveIndicator: palette.white,
  liveIndicatorBackground: "rgba(0, 0, 0, 0.6)",
  liveIndicatorDot: palette.red,
  navBackground: palette.themeSecondary,
  navBackgroundHover: palette.themePrimary,
  spinner: palette.themePrimary,
  switchTrack: palette.dark,
  switchThumb: palette.black,
  switchActiveTrack: palette.dark,
  switchActiveThumb: palette.themePrimary,
};
