import palette from "./palette";

export default {
  bodyBackground: palette.white,
  bodyText: palette.black,
  bodySubtext: palette.dark,
  border: palette.light,
  link: palette.themePrimary,
  linkHover: palette.themeSecondary,
  heading: palette.dark,
  itemPrimary: palette.black,
  itemSecondary: palette.dark,
  itemPrimaryHover: palette.white,
  itemSecondaryHover: palette.light,
  itemBackground: palette.light,
  itemBackgroundHover: palette.dark,
  itemShadowHover: "rgba(0, 0, 0, 0.1)",
  liveIndicator: palette.white,
  liveIndicatorBackground: "rgba(0, 0, 0, 0.6)",
  liveIndicatorDot: palette.red,
  navBackground: palette.themeSecondary,
  navBackgroundHover: palette.themePrimary,
  spinner: palette.themePrimary,
  switchTrack: palette.light,
  switchThumb: palette.white,
  switchActiveTrack: palette.light,
  switchActiveThumb: palette.themePrimary,
};
