export default {
  borderLarge: 6,
  borderMedium: 3,
  borderSmall: 1,
  borderRadiusLarge: 12,
  borderRadiusMedium: 6,
  borderRadiusSmall: 2,
  gapLarge: 20,
  gapMedium: 10,
  gapSmall: 5,
  navSize: 32,
  spinnerSize: 36,
  maxGameWidth: 188,
  maxGameHeight: 250,
  maxStreamWidth: 400,
  maxStreamHeight: 225,
};
